//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpBurp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:1337")]
        public string BurpUrl {
            get {
                return ((string)(this["BurpUrl"]));
            }
            set {
                this["BurpUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApiKey {
            get {
                return ((string)(this["ApiKey"]));
            }
            set {
                this["ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedScanConfiguration {
            get {
                return ((string)(this["SelectedScanConfiguration"]));
            }
            set {
                this["SelectedScanConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Add all links to site map</string>
  <string>Add requested item to site map</string>
  <string>Audit checks - all except JavaScript analysis</string>
  <string>Audit checks - all except time-based detection methods</string>
  <string>Audit checks - critical issues only</string>
  <string>Audit checks - extensions only</string>
  <string>Audit checks - light active</string>
  <string>Audit checks - medium active</string>
  <string>Audit checks - passive</string>
  <string>Audit coverage - maximum</string>
  <string>Audit coverage - thorough</string>
  <string>Crawl limit - 10 minutes</string>
  <string>Crawl limit - 30 minutes</string>
  <string>Crawl limit - 60 minutes</string>
  <string>Crawl strategy - faster</string>
  <string>Crawl strategy - fastest</string>
  <string>Crawl strategy - more complete</string>
  <string>Crawl strategy - most complete</string>
  <string>HTTP Request Smuggling</string>
  <string>Minimize false negatives</string>
  <string>Minimize false positives</string>
  <string>Never stop audit due to application errors</string>
  <string>Never stop crawl due to application errors</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ScanConfigurations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ScanConfigurations"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default resource pool")]
        public string ResourcePool {
            get {
                return ((string)(this["ResourcePool"]));
            }
            set {
                this["ResourcePool"] = value;
            }
        }
    }
}
